package kamailio_cfg

// SIPHeaders is a list of standard SIP (Session Initiation Protocol) headers.
// These headers are used in SIP messages to convey various types of information
// such as the type of request, the sender, the recipient, and other metadata.
var SIPHeaders = map[string]string{
	"Accept":                   "Indicates media types that are acceptable for the response. [RFC3261]",
	"Accept-Contact":           "Specifies the desired characteristics of the contact address. [RFC3841]",
	"Accept-Encoding":          "Indicates content-coding values that are acceptable in the response. [RFC3261]",
	"Accept-Language":          "Indicates the preferred languages for the response. [RFC3261]",
	"Accept-Resource-Priority": "Indicates the desired resource priority. [RFC4412]",
	"Additional-Identity":      "Provides additional identity information. [RFC8224]",
	"Alert-Info":               "Provides a URI to a resource that can be rendered to alert the user. [RFC3261]",
	"AlertMsg-Error":           "Indicates an error in the alert message. [RFC3261]",
	"Allow":                    "Lists the methods supported by the server. [RFC3261]",
	"Allow-Events":             "Lists the event packages supported by the server. [RFC6665]",
	"Answer-Mode":              "Indicates the desired answer mode for the call. [RFC5373]",
	"Attestation-Info":         "Provides attestation information for the call. [RFC8224]",
	"Authentication-Info":      "Provides additional authentication information. [RFC2617]",
	"Authorization":            "Contains credentials for authenticating the user agent. [RFC3261]",
	"Call-ID":                  "Uniquely identifies a particular invitation or all registrations of a client. [RFC3261]",
	"Call-Info":                "Provides additional information about the call. [RFC3261]",
	"Cellular-Network-Info":    "Provides information about the cellular network. [RFC3455]",
	"Contact":                  "Indicates the SIP URI that should be used to contact the user. [RFC3261]",
	"Content-Disposition":      "Indicates how the message body or a message body part is to be interpreted. [RFC3261]",
	"Content-Encoding":         "Indicates the encoding transformations that have been applied to the message body. [RFC3261]",
	"Content-ID":               "Provides a unique identifier for the message body. [RFC3261]",
	"Content-Language":         "Indicates the language of the message body. [RFC3261]",
	"Content-Length":           "Indicates the size of the message body in octets. [RFC3261]",
	"Content-Type":             "Indicates the media type of the message body. [RFC3261]",
	"CSeq":                     "Contains an integer and a method name that uniquely identify a request. [RFC3261]",
	"Date":                     "Contains the date and time at which the message was originated. [RFC3261]",
	"Encryption (Deprecated)":  "Indicates that the message body is encrypted. [RFC3261]",
	"Error-Info":               "Provides a URI to additional information about the error. [RFC3261]",
	"Event":                    "Indicates the type of event being reported. [RFC6665]",
	"Expires":                  "Indicates the time after which the message is considered stale. [RFC3261]",
	"Feature-Caps":             "Indicates the capabilities of the user agent. [RFC6809]",
	"Flow-Timer":               "Indicates the flow timer value. [RFC5626]",
	"From":                     "Indicates the logical identity of the initiator of the request. [RFC3261]",
	"Geolocation":              "Provides geolocation information. [RFC6442]",
	"Geolocation-Error":        "Indicates an error in the geolocation information. [RFC6442]",
	"Geolocation-Routing":      "Indicates routing information for geolocation. [RFC6442]",
	"Hide (Deprecated)":        "Indicates that the request should be hidden. [RFC3323]",
	"History-Info":             "Provides information about the history of the request. [RFC7044]",
	"Identity":                 "Provides identity information for the request. [RFC8224]",
	"Identity-Info (deprecated by [RFC8224])": "Provides additional identity information. [RFC8224]",
	"Info-Package":                  "Indicates the info package being used. [RFC6086]",
	"In-Reply-To":                   "Identifies the message to which this one is a reply. [RFC3261]",
	"Join":                          "Indicates that the request is joining an existing dialog. [RFC3911]",
	"Max-Breadth":                   "Indicates the maximum breadth of the request. [RFC5393]",
	"Max-Forwards":                  "Indicates the maximum number of hops that the request can traverse. [RFC3261]",
	"MIME-Version":                  "Indicates the version of the MIME protocol. [RFC2045]",
	"Min-Expires":                   "Indicates the minimum expiration time. [RFC3261]",
	"Min-SE":                        "Indicates the minimum session expiration time. [RFC4028]",
	"Organization":                  "Indicates the organization to which the user belongs. [RFC3261]",
	"Origination-Id":                "Provides an identifier for the origination of the request. [RFC7375]",
	"P-Access-Network-Info":         "Provides information about the access network. [RFC7315]",
	"P-Answer-State":                "Indicates the answer state of the request. [RFC7315]",
	"P-Asserted-Identity":           "Provides the asserted identity of the user. [RFC3325]",
	"P-Asserted-Service":            "Provides the asserted service of the user. [RFC7315]",
	"P-Associated-URI":              "Provides the associated URI of the user. [RFC7315]",
	"P-Called-Party-ID":             "Provides the called party identifier. [RFC3455]",
	"P-Charge-Info":                 "Provides charging information. [RFC3455]",
	"P-Charging-Function-Addresses": "Provides the addresses of the charging functions. [RFC7315]",
	"P-Charging-Vector":             "Provides the charging vector. [RFC7315]",
	"P-DCS-Trace-Party-ID":          "Provides the trace party identifier. [RFC5503]",
	"P-DCS-OSPS":                    "Provides the OSPS information. [RFC5503]",
	"P-DCS-Billing-Info":            "Provides billing information. [RFC5503]",
	"P-DCS-LAES":                    "Provides lawful intercept information. [RFC5503]",
	"P-DCS-Redirect":                "Provides redirect information. [RFC5503]",
	"P-Early-Media":                 "Indicates early media information. [RFC5009]",
	"P-Media-Authorization":         "Provides media authorization information. [RFC3313]",
	"P-Preferred-Identity":          "Provides the preferred identity of the user. [RFC3325]",
	"P-Preferred-Service":           "Provides the preferred service of the user. [RFC7315]",
	"P-Private-Network-Indication":  "Indicates a private network. [RFC7315]",
	"P-Profile-Key":                 "Provides the profile key. [RFC5002]",
	"P-Refused-URI-List":            "Provides a list of refused URIs. [RFC5318]",
	"P-Served-User":                 "Provides the served user information. [RFC5502]",
	"P-User-Database":               "Provides the user database information. [RFC5503]",
	"P-Visited-Network-ID":          "Provides the visited network identifier. [RFC5503]",
	"Path":                          "Indicates the path of the request. [RFC3327]",
	"Permission-Missing":            "Indicates missing permissions. [RFC5503]",
	"Policy-Contact":                "Provides policy contact information. [RFC5503]",
	"Policy-ID":                     "Provides the policy identifier. [RFC5503]",
	"Priority":                      "Indicates the priority of the request. [RFC3261]",
	"Priority-Share":                "Indicates the priority share. [RFC5503]",
	"Priority-Verstat":              "Indicates the priority verification status. [RFC5503]",
	"Priv-Answer-Mode":              "Indicates the private answer mode. [RFC5503]",
	"Privacy":                       "Indicates the privacy level of the request. [RFC3323]",
	"Proxy-Authenticate":            "Indicates the authentication scheme and parameters. [RFC3261]",
	"Proxy-Authorization":           "Contains credentials for authenticating the user agent to the proxy. [RFC3261]",
	"Proxy-Require":                 "Indicates proxy-sensitive features required by the client. [RFC3261]",
	"RAck":                          "Provides reliability information for provisional responses. [RFC3262]",
	"Reason":                        "Indicates the reason for the request. [RFC3326]",
	"Reason-Phrase":                 "Provides a textual description of the status code. [RFC3261]",
	"Record-Route":                  "Indicates the route that the request has traversed. [RFC3261]",
	"Recv-Info":                     "Indicates the information to be received. [RFC6086]",
	"Refer-Events-At":               "Indicates the events at which the refer is valid. [RFC4488]",
	"Refer-Sub":                     "Indicates the subscription state of the refer. [RFC4488]",
	"Refer-To":                      "Indicates the target of the refer. [RFC3515]",
	"Referred-By":                   "Indicates the referring party. [RFC3515]",
	"Reject-Contact":                "Indicates the contact to be rejected. [RFC3841]",
	"Relayed-Charge":                "Indicates the relayed charge information. [RFC5503]",
	"Replaces":                      "Indicates the dialog to be replaced. [RFC3891]",
	"Reply-To":                      "Indicates the reply-to address. [RFC3261]",
	"Request-Disposition":           "Indicates the desired handling of the request. [RFC3841]",
	"Require":                       "Indicates required features. [RFC3261]",
	"Resource-Priority":             "Indicates the resource priority. [RFC4412]",
	"Resource-Share":                "Indicates the resource share. [RFC5503]",
	"Response-Key (Deprecated)":     "Indicates the response key. [RFC3261]",
	"Response-Source":               "Indicates the source of the response. [RFC5503]",
	"Restoration-Info":              "Provides restoration information. [RFC5503]",
	"Retry-After":                   "Indicates the time after which the request can be retried. [RFC3261]",
	"Route":                         "Indicates the route to be followed by the request. [RFC3261]",
	"RSeq":                          "Provides reliability information for provisional responses. [RFC3262]",
	"Security-Client":               "Indicates the security mechanisms supported by the client. [RFC3329]",
	"Security-Server":               "Indicates the security mechanisms supported by the server. [RFC3329]",
	"Security-Verify":               "Indicates the security mechanisms to be verified. [RFC3329]",
	"Server":                        "Indicates the server software used by the server. [RFC3261]",
	"Service-Interact-Info":         "Provides service interaction information. [RFC5503]",
	"Service-Route":                 "Indicates the service route. [RFC3608]",
	"Session-Expires":               "Indicates the session expiration time. [RFC4028]",
	"Session-ID":                    "Provides the session identifier. [RFC5503]",
	"SIP-ETag":                      "Provides the SIP entity tag. [RFC3903]",
	"SIP-If-Match":                  "Provides the SIP if-match information. [RFC3903]",
	"Subject":                       "Indicates the subject of the request. [RFC3261]",
	"Subscription-State":            "Indicates the subscription state. [RFC6665]",
	"Supported":                     "Indicates supported features. [RFC3261]",
	"Suppress-If-Match":             "Indicates the suppress-if-match information. [RFC5503]",
	"Target-Dialog":                 "Indicates the target dialog. [RFC4538]",
	"Timestamp":                     "Indicates the timestamp of the request. [RFC3261]",
	"To":                            "Indicates the logical identity of the recipient of the request. [RFC3261]",
	"Trigger-Consent":               "Indicates the trigger consent information. [RFC5503]",
	"Unsupported":                   "Indicates unsupported features. [RFC3261]",
	"User-Agent":                    "Indicates the user agent software used by the client. [RFC3261]",
	"User-to-User":                  "Provides user-to-user information. [RFC7433]",
	"Via":                           "Indicates the path taken by the request. [RFC3261]",
	"Warning":                       "Provides additional information about the status of the request. [RFC3261]",
	"WWW-Authenticate":              "Indicates the authentication scheme and parameters. [RFC3261]",
}
